### ISSUE TITLE
S&H: drho_dz is used as an approximation for drhod_dz for computing rhod profile (test needed)

### ISSUE THREAD

**Issue by sajjadazimi** [atmos-cloud-sim-uj/MPyDATA#335]
The correct rhod profile can be computed:

drhod/dz = d/dz (rho / (1+qv)) = drho/dz / (1+qv) - rhod * dqv/dz / (1+qv)

**Comment by slayoo** [comment]
this is addressed here: https://github.com/atmos-cloud-sim-uj/PyMPDATA-examples/pull/65
