### ISSUE TITLE
Logo for PyMPDATA

### ISSUE THREAD

**Issue by NeKo2903** [atmos-cloud-sim-uj/MPyDATA#432]
Hi everyone,

I’ve created four logo designs for the PyMPDATA library and would love your input on which one you think is the best fit. The key question is where Psi and Nabla are best distinguishable.
Your feedback would be greatly appreciated!

ver1:
![4](https://github.com/user-attachments/assets/5b0ad2d3-e3c0-4787-a6eb-728e46490dec)

ver 2:
![3](https://github.com/user-attachments/assets/0a754b07-2ddc-4fdd-92dd-7314fa5c4083)

ver 3:
![2](https://github.com/user-attachments/assets/2a23ae8a-16d2-4a76-9147-d6e535f39b53)

ver 4:
![1](https://github.com/user-attachments/assets/6b791a6a-66f4-49f9-81e7-33a4dbd90e84)
it's version 1 but with Numba reference

**Comment by slayoo** [comment]
Kudos @NeKo2903!
@piotrbartman, @Delcior, @xann16, @edejong-caltech, @trontrytel, @rlhycd, @sajjadazimi, @Kojec1, @abulenok - feedback welcome, please vote/comment, thanks!

**Comment by rlhycd** [comment]
All of them looking great, v2 and v3 are my favourites though :)

**Comment by Delcior** [comment]
Great work @NeKo2903! Every proposition has its uniqueness. My favourite though is v1 and v3.

**Comment by trontrytel** [comment]
Very cool! I like v2 the best.

**Comment by abulenok** [comment]
Looks nice! My favorite is v2

**Comment by xann16** [comment]
Aesthetically - against the majority - I like v4 (due to Numba reference), but I can see the point for v2 (due to its simplicity and clarity).

**Comment by piotrbartman** [comment]
v2 and v3 are the best for PyMPDATA

**Comment by slayoo** [comment]
I'm adding +1 for v4 :)

And, so far we have:
- v1: +
- v2: +++++
- v3: +++
- v4: ++

Shall we close the vote and declare v2 the winner?

**Comment by slayoo** [comment]
Thank you All for voting and feedback!
Logo PR merged, here's how it looks in README and the docs:
![image](https://github.com/user-attachments/assets/636dcf75-bf62-416c-ba97-89b2f059685d)
![image](https://github.com/user-attachments/assets/b18a5799-40bb-4891-add0-0f81e5711e4a)

Kudos @NeKo2903!

**Comment by slayoo** [comment]
and here's how it look on PyPI (there's some room for improvement in terms of page layout...):
![image](https://github.com/user-attachments/assets/7c39b3be-5711-4124-a043-a3050cdded9f)
